name: Ejemplo CI/CD

on:
  push:

jobs:
  inicio:
    runs-on: windows-latest
    steps:
      - name: Mostrar texto
        run: echo "Inicio del flujo de trabajo"
      - name: Checkout
        uses: actions/checkout@v4.2.2  
      
jobs:
  build:
    runs-on: windows-latest
    needs: [inicio]
    steps:
      - name: Mostrar texto
        run: echo "Construir"
        
      - name: Instalar PHP y Composer en Windows
        run: |
          choco install php --version=8.1
          choco install composer 
          php -v
          composer --version
      - name: Instalar dependencias
        run: |
          choco install mysql --version8.0  


  test:
    runs-on: windows-latest
    needs: [inicio]
    steps:
      - name: Pruebas
        run: echo "Pruebas ejecutadas"

  deploy:
    runs-on: windows-latest
    needs: [inicio]
    steps:
      - name: Despliegue
        run: echo "Despliegue completado"

