name: Ejemplo CI/CD

on:
  push:

jobs:
  inicio:
    runs-on: windows-latest
    steps:
      - name: Mostrar texto
        run: echo "Paso para clonar repositorio a GitHub Actions"
      - name: Checkout
        uses: actions/checkout@v4.2.2

  build:
    runs-on: windows-latest
    needs: [inicio]
    steps:
      - name: Mostrar texto
        run: echo "Construir"
      - name: Instalar PHP y Composer en Windows
        run: |
          choco install php --version=8.1
          choco install composer
          php -v
          composer --version
      - name: Instalar MySql
        run: |
          choco install mysql --version=8.0
          Start-Service mysqls

  test:
    runs-on: windows-latest
    needs: [build]
    steps:
      - name: Mostrar texto
        run: echo "Ejecutar pruebas"

  deploy:
    runs-on: windows-latest
    needs: [test]
    steps:
      - name: Mostrar texto
        run: echo "Desplegar aplicación"