name: Ejemplo CI/CD

on:
  push:

jobs:
  inicio:
    runs-on: windows-latest
    steps:
      - name: Mostrar texto
        run: echo "Inicio del flujo de trabajo"

  build:
    runs-on: windows-latest
    needs: [inicio]
    steps:
      - name: Construir
        run: echo "Construcción completada"

  test:
    runs-on: windows-latest
    needs: [inicio]
    steps:
      - name: Pruebas
        run: echo "Pruebas ejecutadas"

  deploy:
    runs-on: windows-latest
    needs: [inicio]
    steps:
      - name: Despliegue
        run: echo "Despliegue completado"

